{
 "title": "Idun Common Services - Container Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "label": "Environment", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Common-Service API-Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API-Gateway - CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "yaxes": [
    { "format": "cores", "label": "core" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"eric-eo-api-gateway\"}[15m])",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"eric-eo-api-gateway\"}) ",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"eric-eo-api-gateway\"}) ",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "API-Gateway - Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"eric-eo-api-gateway\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"eric-eo-api-gateway\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", container=\"eric-eo-api-gateway\"}",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "API-Gateway - Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"^eric-eo-api-gateway-.*\", interface=\"eth0\"}[15m])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-eo-api-gateway-.*\", interface=\"eth0\"}[15m])",
     "legendFormat": "Transmitted"
    }
   ]
  },
  { "title": "Common-Service BR-Agent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Common-BR-Agent - CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"common-br-agent\"}[15m])",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"common-br-agent\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"common-br-agent\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Common-BR-Agent - Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"common-br-agent\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"common-br-agent\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"eric-eo-api-gateway\"}",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Common-BR-Agent - Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"^eric-eo-common-br-agent-.*\", interface=\"eth0\"}[15m])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-eo-common-br-agent-.*\", interface=\"eth0\"}[15m])",
     "legendFormat": "Transmitted"
    }
   ]
  },
  { "title": "Common-Service Logviewer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Logviewer  - CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "yaxes": [
    { "format": "cores", "label": "core" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"kibana\"}[15m])",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"kibana\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"kibana\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Logviewer - Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"kibana\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"kibana\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"kibana\"}",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Logviewer -- Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"^eric-data-visualizer-kb-.*\", interface=\"eth0\"}[15m])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-data-visualizer-kb-.*\", interface=\"eth0\"}[15m])",
     "legendFormat": "Transmitted"
    }
   ]
  },
  { "title": "ADP-Logstransformer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Logtransformer - CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"logtransformer\"}[15m])",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"logtransformer\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"logtransformer\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Logtransformer - Memory ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"logtransformer\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"logtransformer\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"logtransformer\"}",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Logtransformer - Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"^eric-log-transformer-.*\", interface=\"eth0\"}[15m])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-log-transformer-.*\", interface=\"eth0\"}[15m])",
     "legendFormat": "Transmitted"
    }
   ]
  },
  { "title": "ADP-Logshipper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Logshipper - CPU ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"logshipper\"}[15m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"logshipper\"}))",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"logshipper\"}))",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Logshipper  - Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"logshipper\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"logshipper\"}))",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"logshipper\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Logshipper - Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"^eric-log-shipper-.*\", interface=\"eth0\"}[15m]))",
     "legendFormat": "Received "
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-log-shipper-.*\", interface=\"eth0\"}[15m]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  { "title": "ADP-Search Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Search Engine-  CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "yaxes": [
    { "format": "cores", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"eric-eo-engine\"}[15m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"eric-eo-engine\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"eric-eo-engine\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Search Engine - Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"eric-eo-engine\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\",container=\"eric-eo-engine\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"eric-eo-engine\"}",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Search Engine - Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"^eric-data-search-.*\", interface=\"eth0\"}[15m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "\r\nsum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-data-search-.*\", interface=\"eth0\"}[15m]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  { "title": "ADP-KeyCloak", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "KeyCloak - CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "yaxes": [
    { "format": "cores", "label": "core" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=~\"iam\"}[15m])",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"iam\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"iam\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "KeyCloak - Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"iam\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"iam\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"iam\"}",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "KeyCloak - Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"^^eric-sec-access-mgmt-.*\", interface=\"eth0\"}[15m])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-sec-access-mgmt-.*\", interface=\"eth0\"}[15m])",
     "legendFormat": "Transmitted"
    }
   ]
  },
  { "title": "ADP - Eric-Ctrl-Bro", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Eric-Ctrl-Bro - Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"eric-ctrl-bro\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\",container=\"eric-ctrl-bro\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"eric-ctrl-bro\"}",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Eric-Ctrl-Bro - CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"eric-ctrl-bro\"}[15m])",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", container=\"eric-ctrl-bro\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"eric-ctrl-bro\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Eric-Ctrl-Bro - Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"^eric-ctrl-bro-.*\", interface=\"eth0\"}[15m])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^eric-ctrl-bro-.*\", interface=\"eth0\"}[15m])",
     "legendFormat": "Transmitted"
    }
   ]
  }
 ]
}