{
 "title": "IDUN aaS Overall Monitoring Alert Dashboard",
 "description": "Alerts dashboard for overall monitoring of pods failed, jobs failed, deployment replicaset unavailable, nodes unavailable and running pvc's about 70%. If threshold breached, then send alert email.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "BNEWIDUN01 Overall Monitoring Alert",
   "type": "graph",
   "description": "BNEWIDUN01 Alert Dashboard for pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace oss and running pvc's above 70% for the environment BNEW01 ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"oss\", phase=\"Failed\"})",
     "legendFormat": "Pods Failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"oss\"})",
     "legendFormat": "Jobs Failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"oss\"})",
     "legendFormat": "Deployment Replica Unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"ip-[0-9]{3}-[0-9]{2}-[0-9]{2}-[0-9]{1,3}.*\"})",
     "legendFormat": "Nodes Unavailable"
    },
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= (70 / 100)) or vector (0)",
     "legendFormat": "Running PVCs Above 70%   "
    },
    {
     "expr": "sum(0 < ((x509_cert_not_after{job=\"certificates-exporter\", subject_O=~\"Ericsson.*\"} - time()) / 86400) < bool 7)",
     "legendFormat": "Certificate expiring within 7 days"
    },
    {
     "expr": "sum(0 < ((x509_cert_not_after{job=\"certificates-exporter\", subject_O=~\"Ericsson.*\"} - time()) / 86400) < bool 30)",
     "legendFormat": "Certificate expiring within 30 days"
    }
   ]
  },
  {
   "title": "BNEWIDUN02 Overall Monitoring Alert",
   "type": "graph",
   "description": "BNEWIDUN02 Alert Dashboard for pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace ossbnew02 and running pvc's above 70% for the environment BNEW02",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ossbnew02\", phase=\"Failed\"})",
     "legendFormat": "Pods Failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"ossbnew02\"})",
     "legendFormat": "Jobs Failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"ossbnew02\"})",
     "legendFormat": "Deployment Replica Unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"ip-[0-9]{3}-[0-9]{2}-[0-9]{2}-[0-9]{1,3}.*\"})",
     "legendFormat": "Nodes Unavailable"
    },
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= (70 / 100)) or vector (0)",
     "legendFormat": "Running PVCs Above 70%"
    }
   ]
  },
  {
   "title": "BNEWIDUN03 Overall Monitoring Alert",
   "type": "graph",
   "description": "BNEWIDUN03 Alert Dashboard for pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace ossbnew03 and running pvc's above 70% for the environment BNEW03",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ossbnew03\", phase=\"Failed\"})",
     "legendFormat": "Pods Failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"ossbnew03\"})",
     "legendFormat": "Jobs Failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"ossbnew03\"})",
     "legendFormat": "Deployment Replica Unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"ip-[0-9]{3}-[0-9]{2}-[0-9]{2}-[0-9]{1,3}.*\"})",
     "legendFormat": "Nodes Unavailable"
    },
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= (70 / 100)) or vector (0)",
     "legendFormat": "Running PVCs Above 70%   "
    }
   ]
  },
  {
   "title": "OPENLAB01 Overall Monitoring Alert",
   "type": "graph",
   "description": "OPENLAB01 Alert Dashboard for pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace oss and running pvc's above 70% for the environment BNEW01 ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"idunopenlab01\", phase=\"Failed\", pod!~\"eric-data-search-engine-curator.+\"})",
     "legendFormat": "Pods Failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"idunopenlab01\", job_name!~\"eric-data-search-engine-curator.+\"})",
     "legendFormat": "Jobs Failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"idunopenlab01\"})",
     "legendFormat": "Deployment Replica Unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"ip-[0-9]{3}-[0-9]{2}-[0-9]{1,3}-[0-9]{1,3}.*\"})",
     "legendFormat": "Nodes Unavailable"
    },
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= (70 / 100)) or vector (0)",
     "legendFormat": "Running PVCs Above 70%   "
    }
   ]
  },
  {
   "title": "CRANSCOEIAP01 Overall Monitoring Alert",
   "type": "graph",
   "description": "CRANSCOEIAP01 Alert Dashboard for pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace osscransco01 and running pvc's above 70% for the environment ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"osscransco01\", phase=\"Failed\"})",
     "legendFormat": "Pods Failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"osscransco01\"})",
     "legendFormat": "Jobs Failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"osscransco01\"})",
     "legendFormat": "Deployment Replica Unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"ip-[0-9]{3}-[0-9]{2}-[0-9]{3}-[0-9]{1,3}.*\"})",
     "legendFormat": "Nodes Unavailable"
    },
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= (71 / 100)) or vector (0)",
     "legendFormat": "Running PVCs Above 70%"
    }
   ]
  },
  {
   "title": "OSSAUTOAPP01 Overall Monioring Alert",
   "type": "graph",
   "description": "OSSAUTOAPP01 Overall Monioring Alert for Pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace idunossautoapp01 and running pvc's above 70% for the environment OSSAUTOAPP01 ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"idunossautoapp01\", phase=\"Failed\"})",
     "legendFormat": "Pods Failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"idunossautoapp01\"})",
     "legendFormat": "Jobs Failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"idunossautoapp01\"})",
     "legendFormat": "Deployment Replica Unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"ip-[0-9]{3}-[0-9]{2}-[0-9]{3}-[0-9]{1,3}.*\"})",
     "legendFormat": "Nodes Unavailable"
    },
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= (70 / 100)) or vector (0)",
     "legendFormat": "Running PVCs Above 70%"
    }
   ]
  },
  {
   "title": "BMASIDUN01 Overall Monitoring Alert",
   "type": "graph",
   "description": "BMASIDUN01 Alert Dashboard for pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace ossbmas01 and running pvc's above 70% for the environment BMAS01",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ossbmas01\", phase=\"Failed\"})",
     "legendFormat": "Pods Failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"ossbmas01\"})",
     "legendFormat": "Jobs Failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"ossbmas01\"})",
     "legendFormat": "Deployment Replica Unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"ip-[0-9]{3}-[0-9]{2}-[0-9]{2}-[0-9]{1,3}.*\"})",
     "legendFormat": "Nodes Unavailable"
    },
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= (70 / 100)) or vector (0)",
     "legendFormat": "Running PVCs Above 70%   "
    },
    {
     "expr": "sum(0 < ((x509_cert_not_after{job=\"certificates-exporter\", subject_O=~\"Ericsson.*\"} - time()) / 86400) < bool 7)",
     "legendFormat": "Certificates expiring within 7 days"
    },
    {
     "expr": "sum(0 < ((x509_cert_not_after{job=\"certificates-exporter\", subject_O=~\"Ericsson.*\"} - time()) / 86400) < bool 30)",
     "legendFormat": "Certificates expiring within 30 days"
    }
   ]
  },
  {
   "title": "VIAVIEIAP01 Overall Monitoring Alert",
   "type": "graph",
   "description": "VIAVIEIAP01 Alert Dashboard for pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace oss and running pvc's above 70% for the environment BNEW01 ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ossviavi01\", phase=\"Failed\"})",
     "legendFormat": "Pods Failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"ossviavi01\"})",
     "legendFormat": "Jobs Failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"ossviavi01\"})",
     "legendFormat": "Deployment Replica Unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"ip-[0-9]{3}-[0-9]{2}-[0-9]{1,3}-[0-9]{1,3}.*\"})",
     "legendFormat": "Nodes Unavailable"
    },
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= (70 / 100)) or vector (0)",
     "legendFormat": "Running PVCs Above 70%   "
    }
   ]
  },
  {
   "title": "ERNIDUN01 Overall Monitoring Alert",
   "type": "graph",
   "description": "ERNIDUN01 Alert Dashboard for pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace ossern01 and running pvc's above 70% for the environment ERN01 ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ossern01\", phase=\"Failed\"})",
     "legendFormat": "Pods Failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"ossern01\"})",
     "legendFormat": "Jobs Failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"ossern01\"})",
     "legendFormat": "Deployment Replica Unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"ip-[0-9]{3}-[0-9]{2}-[0-9]{2}-[0-9]{1,3}.*\"})",
     "legendFormat": "Nodes Unavailable"
    },
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= (70 / 100)) or vector (0)",
     "legendFormat": "Running PVCs Above 70%   "
    }
   ]
  },
  {
   "title": "ECOSYSTEM01 Overall Monitoring Alert",
   "type": "graph",
   "description": "ECOSYSTEM01 Alert Dashboard for pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace ossecos01 and running pvc's above 70% for the environment",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ossecos01\", phase=\"Failed\"})",
     "legendFormat": "Pods Failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"ossecos01\"})",
     "legendFormat": "Jobs Failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"ossecos01\"})",
     "legendFormat": "Deployment Replica Unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"ip-[0-9]{3}-[0-9]{2}-[0-9]{2}-[0-9]{1,3}.*\"})",
     "legendFormat": "Nodes Unavailable"
    },
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= (71 / 100)) or vector (0)",
     "legendFormat": "Running PVCs Above 70%"
    }
   ]
  },
  {
   "title": "PROTOTYPE01 Overall Monitoring Alert",
   "type": "graph",
   "description": "PROTOTYPE01 Alert Dashboard for pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace ossprototype01 and running pvc's above 70% for the environment",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ossprototype01\", phase=\"Failed\"})",
     "legendFormat": "Pods Failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"ossprototype01\"})",
     "legendFormat": "Jobs Failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"ossprototype01\"})",
     "legendFormat": "Deployment Replica Unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"ip-[0-9]{3}-[0-9]{2}-[0-9]{2}-[0-9]{1,3}.*\"})",
     "legendFormat": "Nodes Unavailable"
    },
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= (70 / 100)) or vector (0)",
     "legendFormat": "Running PVCs Above 70%"
    }
   ]
  }
 ]
}