{
 "title": "Subsystem Fault Check",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "BNEW - Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(bnew1_enm_ui_health_status{hostname=\"stsvp3aenm01-10.stsoss.sero.gic.ericsson.se\"})",
     "legendFormat": "stsvp3aenm01-10.stsoss.sero.gic.ericsson.se"
    },
    {
     "expr": "avg(bnew1_eocm_ui_health_status{hostname=\"stsvp3aeocm01-102.stsoss.sero.gic.ericsson.se\"})",
     "legendFormat": "stsvp3aeocm01-102.stsoss.sero.gic.ericsson.se"
    },
    {
     "expr": "avg(bnew1_evnfm_ui_health_status{hostname=\"evnfm01.stsvp3accd01.stsoss.sero.gic.ericsson.se\"})",
     "legendFormat": "evnfm01.stsvp3accd01.stsoss.sero.gic.ericsson.se"
    }
   ]
  },
  {
   "title": "BNEW - ENM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bnew1_enm_ui_health_status{hostname=\"stsvp3aenm01-10.stsoss.sero.gic.ericsson.se\"})",
     "legendFormat": "ENM"
    }
   ]
  },
  {
   "title": "BNEW - EOCM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bnew1_eocm_ui_health_status{hostname=\"stsvp3aeocm01-102.stsoss.sero.gic.ericsson.se\"})",
     "legendFormat": "EOCM"
    }
   ]
  },
  {
   "title": "BNEW - EVNFM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bnew1_evnfm_ui_health_status{hostname=\"evnfm01.stsvp3accd01.stsoss.sero.gic.ericsson.se\"})",
     "legendFormat": "EVNFM"
    }
   ]
  },
  {
   "title": "OSSAutoApp - Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "avg(ossautoapp_enm_ui_health_status{hostname=\"stsvp6aenm01-136.stsoss.sero.gic.ericsson.se\"})",
     "legendFormat": "{{hostname}}stsvp6aenm01-136.stsoss.sero.gic.ericsson.se"
    },
    {
     "expr": "avg(ossautoapp_eocm_ui_health_status{hostname=\"stsvp6aeocm01-197.stsoss.sero.gic.ericsson.se\"})",
     "legendFormat": "stsvp6aeocm01-197.stsoss.sero.gic.ericsson.se"
    },
    {
     "expr": "avg(ossautoapp_evnfm_ui_health_status{hostname=\"evnfm01.stsvp6accd01.stsoss.sero.gic.ericsson.se\"})",
     "legendFormat": "evnfm01.stsvp6accd01.stsoss.sero.gic.ericsson.se"
    }
   ]
  },
  {
   "title": "OSSAutoApp - ENM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ossautoapp_enm_ui_health_status{hostname=\"stsvp6aenm01-136.stsoss.sero.gic.ericsson.se\"})",
     "legendFormat": "ENM"
    }
   ]
  },
  {
   "title": "OSSAutoApp - EOCM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ossautoapp_eocm_ui_health_status{hostname=\"stsvp6aeocm01-197.stsoss.sero.gic.ericsson.se\"})",
     "legendFormat": "EOCM"
    }
   ]
  },
  {
   "title": "OSSAutoApp - EVNFM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ossautoapp_evnfm_ui_health_status{hostname=\"evnfm01.stsvp6accd01.stsoss.sero.gic.ericsson.se\"})",
     "legendFormat": "EVNFM"
    }
   ]
  },
  {
   "title": "Openlab - Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "enm_ui_health_status{hostname=\"stsvp7enm06.stsoss.sero.xgic.ericsson.se\"}",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "eocm_ui_health_status{hostname=\"stsvp7ecm01-46.stsoss.sero.xgic.ericsson.se\"}",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "evnfm_ui_health_status{hostname=\"stsvp7ecm02-c.stsoss.sero.xgic.ericsson.se\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Openlab - ENM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "enm_ui_health_status{hostname=\"stsvp7enm06.stsoss.sero.xgic.ericsson.se\"}",
     "legendFormat": "ENM"
    }
   ]
  },
  {
   "title": "Openlab - EOCM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "enm_ui_health_status{hostname=\"stsvp7enm06.stsoss.sero.xgic.ericsson.se\"}",
     "legendFormat": "ENM"
    }
   ]
  },
  {
   "title": "Openlab - EVNFM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evnfm_ui_health_status{hostname=\"stsvp7ecm02-c.stsoss.sero.xgic.ericsson.se\"}",
     "legendFormat": "EVNFM"
    }
   ]
  },
  {
   "title": "ERN - Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(ern01_enm_ui_health_status{hostname=\"v5cenm07.stsoss.seli.gic.ericsson.se\"})",
     "legendFormat": "v5cenm07.stsoss.seli.gic.ericsson.se"
    }
   ]
  },
  {
   "title": "ERN - ENM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ern01_enm_ui_health_status{hostname=\"v5cenm07.stsoss.seli.gic.ericsson.se\"})",
     "legendFormat": "ENM"
    }
   ]
  }
 ]
}