{
 "title": "EIAPaaS K8s Node View (ECN)",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Environment", "query": "prometheus" },
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "label": "Node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum((avg(irate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"system\"}[15m])) * 100))",
     "legendFormat": "system"
    },
    {
     "expr": "sum((avg(irate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"user\"}[15m])) * 100))",
     "legendFormat": "user"
    },
    {
     "expr": "sum((avg(irate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"iowait\"}[15m])) * 100))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum((avg(irate(node_cpu_seconds_total{kubernetes_node=~\"$node\", mode=\"steal\"}[15m])) * 100))",
     "legendFormat": "steal"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{kubernetes_node=~\"$node\"})",
     "legendFormat": "available"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{kubernetes_node=~\"$node\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum(node_memory_Active_bytes{kubernetes_node=~\"$node\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Load per Node",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{kubernetes_node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Disk Usage and Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{kubernetes_node=~\"$node\"}) by (node)",
     "legendFormat": "{{ kubernetes_node }} --> Free"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{kubernetes_node=~\"$node\"}) by (node) - sum(node_filesystem_free_bytes) by (node))",
     "legendFormat": "{{ kubernetes_node }} --> Usage"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{kubernetes_node=~\"$node\"}[15m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{kubernetes_node=~\"$node\"}[15m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{kubernetes_node=~\"$node\"}[15m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{kubernetes_node=~\"$node\"}[15m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Network Traffic/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{kubernetes_node=~\"$node\"}[15m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{kubernetes_node=~\"$node\"}[15m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Network Errors/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(node_network_receive_errs_total{kubernetes_node=~\"$node\"})",
     "legendFormat": "Receive_error"
    },
    {
     "expr": "sum(node_network_transmit_errs_total{kubernetes_node=~\"$node\"})",
     "legendFormat": "Transmit_error"
    }
   ]
  },
  {
   "title": "Network Packets/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{kubernetes_node=~\"$node\"}[15m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_packets_total{kubernetes_node=~\"$node\"}[15m]))",
     "legendFormat": "Transmit"
    }
   ]
  }
 ]
}