{
 "title": "Idun volume usage",
 "description": "Dashboard of Kubernetes / OpenShift volume information at cluster level as exported by Prometheus connected to Kubernetes / OpenShift.",
 "tags": [
  "openshift",
  "k8s",
  "storage"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_OPENSHIFT_PROMETHEUS", "label": "Environment", "query": "prometheus" },
   {
    "name": "pvc_percent_used_warning_threshold",
    "label": "PVC % Used Warning Threshold",
    "query": "80"
   }
  ]
 },
 "panels": [
  { "title": "Current Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Infrastructure Namespace Volumes Full in Week Based on Daily Use Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)",
     "legendFormat": "alerts"
    }
   ]
  },
  {
   "title": "User Namespace Volumes Full in Week Based on Daily Use Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (\n      (kubelet_volume_stats_available_bytes {namespace!~\"(openshift-.*|kube-.*|default|logging)\"})\n    )\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)",
     "legendFormat": "alerts"
    }
   ]
  },
  { "title": "Dashboard Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 } },
  {
   "title": "Running PVCs Above % Used Warning Threshold",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= ($pvc_percent_used_warning_threshold / 100)) or vector (0)"
    }
   ]
  },
  {
   "title": "Idun Unbound PVCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max (sum by (exported_namespace) (pv_collector_unbound_pvc_count))) or (vector(0))"
    }
   ]
  },
  { "title": "Idun Volume Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Idun Bound PVCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (pv_collector_bound_pvc_count)) or vector(0)"
    }
   ]
  },
  {
   "title": "Idun PVC Stats",
   "type": "table-old",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info"
    },
    {
     "expr": "(1-max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info ) ) unless (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes )) or ((max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info ) ) and (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes )))"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes)"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes )"
    },
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes ))"
    }
   ]
  },
  { "title": "Use", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "All Running PVCs Used Bytes",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ))",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Running PVCs % Used",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) * 100",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  { "title": "Use Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Hourly Volume Use Rate",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes [1h])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Daily Volume Use Rate",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes [1d])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Weekly Volume Use Rate",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes [1w])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  }
 ]
}