{
 "title": "Idun aaS  Overall Monitoring",
 "description": "Summary metrics about containers running on Kubernetes nodes.",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node_bnewidun01", "query": { "query": "label_values(node)" } },
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "" } },
   { "name": "node_bnewidun02", "query": { "query": "label_values(node)" } },
   { "name": "node_ossautoapp", "query": { "query": "label_values(node)" } },
   { "name": "node_ernidun01", "query": { "query": "label_values(node)" } },
   { "name": "node_bnewidun03", "query": { "query": "label_values(node)" } },
   { "name": "node_bmas01", "query": { "query": "label_values(node)" } },
   { "name": "node_cransco01", "query": { "query": "label_values(node)" } },
   { "name": "node_idunopenlab01", "query": { "query": "label_values(node)" } },
   { "name": "node_ossviavi01", "query": { "query": "label_values(node)" } },
   { "name": "node_ossecos01", "query": { "query": "label_values(node)" } },
   { "name": "node_ossinfov01", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  { "title": "aaS Environment Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ds" },
  {
   "title": "BNEW-01 Environment",
   "type": "stat",
   "description": "Pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace oss for the bnewidun01 environment.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"oss\", phase=\"Failed\"})",
     "legendFormat": "Pods failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"oss\"})",
     "legendFormat": "Jobs failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"oss\"})",
     "legendFormat": "deployment_replicas unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node_bnewidun01\"})",
     "legendFormat": "nodes unavailable"
    }
   ]
  },
  {
   "title": "BNEW-02 Environment",
   "type": "stat",
   "description": "Pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace ossbnew02 for the bnewidun02 environment.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ossbnew02\", phase=\"Failed\"})",
     "legendFormat": "Pods failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"ossbnew02\"})",
     "legendFormat": "Jobs failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"ossbnew02\"})",
     "legendFormat": "deployment_replicas unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node_bnewidun02\"})",
     "legendFormat": "nodes unavailable"
    }
   ]
  },
  {
   "title": "BNEW-03 Environment",
   "type": "stat",
   "description": "Pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace ossbnew03 for the bnewidun03 environment.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ossbnew03\", phase=\"Failed\"})",
     "legendFormat": "Pods failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"ossbnew03\"})",
     "legendFormat": "Jobs failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"ossbnew03\"})",
     "legendFormat": "deployment_replicas unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node_bnewidun03\"})",
     "legendFormat": "nodes unavailable"
    }
   ]
  },
  {
   "title": "Openlab Environment",
   "type": "stat",
   "description": "Pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace idunopenlab01 for the openlab environment.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"idunopenlab01\", phase=\"Failed\"})",
     "legendFormat": "Pods failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"idunopenlab01\"})",
     "legendFormat": "Jobs failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"idunopenlab01\"})",
     "legendFormat": "deployment_replicas unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node_idunopenlab01\"})",
     "legendFormat": "nodes unavailable"
    }
   ]
  },
  {
   "title": "OSSAUTOAPP-01 Environment",
   "type": "stat",
   "description": "Pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace idunossautoapp01 for the ossautoapp01 environment.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"idunossautoapp01\", phase=\"Failed\"})",
     "legendFormat": "Pods Failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"idunossautoapp01\"})",
     "legendFormat": "Jobs Failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"idunossautoapp01\"})",
     "legendFormat": "Deployment Replica Unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node_ossautoapp\"})",
     "legendFormat": "Nodes Unavailable"
    }
   ]
  },
  {
   "title": "Viavi Environment",
   "type": "stat",
   "description": "Pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace idunopenlab01 for the openlab environment.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ossviavi01\", phase=\"Failed\"})",
     "legendFormat": "Pods failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"ossviavi01\"})",
     "legendFormat": "Jobs failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"ossviavi01\"})",
     "legendFormat": "deployment_replicas unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node_ossviavi01\"})",
     "legendFormat": "nodes unavailable"
    }
   ]
  },
  {
   "title": "Ecosystem Environment",
   "type": "stat",
   "description": "Pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace idunopenlab01 for the openlab environment.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ossecos01\", phase=\"Failed\"})",
     "legendFormat": "Pods failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"ossecos01\"})",
     "legendFormat": "Jobs failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"ossecos01\"})",
     "legendFormat": "deployment_replicas unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node_ossecos01\"})",
     "legendFormat": "nodes unavailable"
    }
   ]
  },
  {
   "title": "CRANSCO Environment",
   "type": "stat",
   "description": "Pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace idunopenlab01 for the openlab environment.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"osscransco01\", phase=\"Failed\"})",
     "legendFormat": "Pods failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"osscransco01\"})",
     "legendFormat": "Jobs failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"osscransco01\"})",
     "legendFormat": "deployment_replicas unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node_cransco01\"})",
     "legendFormat": "nodes unavailable"
    }
   ]
  },
  {
   "title": "InfoVista Environment",
   "type": "stat",
   "description": "Pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace idunopenlab01 for the openlab environment.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ossinfov01\", phase=\"Failed\"})",
     "legendFormat": "Pods failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"ossinfov01\"})",
     "legendFormat": "Jobs failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"ossinfov01\"})",
     "legendFormat": "deployment_replicas unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node_ossinfov01\"})",
     "legendFormat": "nodes unavailable"
    }
   ]
  },
  {
   "title": "BMAS-01 Environment",
   "type": "stat",
   "description": "Pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace idunossautoapp01 for the ossautoapp01 environment.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ossbmas01\", phase=\"Failed\"})",
     "legendFormat": "Pods Failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"ossbmas01\"})",
     "legendFormat": "Jobs Failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"ossbmas01\"})",
     "legendFormat": "Deployment Replica Unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node_bmas01\"})",
     "legendFormat": "Nodes Unavailable"
    }
   ]
  },
  {
   "title": "ERN-01 Environment",
   "type": "stat",
   "description": "Pods failed, jobs failed, deployment_replicas unavailable, nodes unavailable in the namespace ossbmas01 for the bmasidun01 environment.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"ossern01\", phase=\"Failed\"})",
     "legendFormat": "Pods failed"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"ossern01\"})",
     "legendFormat": "Jobs failed"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"ossern01\"})",
     "legendFormat": "deployment_replicas unavailable"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node_ernidun01\"})",
     "legendFormat": "nodes unavailable"
    }
   ]
  }
 ]
}