{
 "title": "EIAPaaS Certificates",
 "description": "Unified dashboard for checking certificates expiration: Kubernetes Secrets, certificate files on nodes, or on any server.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "prometheus" },
   { "name": "critical_threshold", "label": "Critical Threshold (days)", "query": "1,7,14,15,28,30,60,90,180,365" },
   { "name": "warning_threshold", "label": "Warning Threshold (days)", "query": "1,7,14,15,28,30,60,90,180,365" },
   {
    "name": "list_threshold",
    "label": "List expiring in less than (days)",
    "query": "1,7,15,30,60,90,180,365,730,1095,1460,1825,3650,7300"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"background-color:  #002561;text-align: center\">\n   EIAPaaS Deployments Certificates Dashboard\n</h1>\n<p style=\"font-style: italic\">Certificate Dashboard for EIAPaaS Deployments</p>\n<hr width=\"100%\" />\n<br>\n"
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total Certificates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(x509_cert_not_after{job=\"certificates-exporter\", subject_O=~\"Ericsson.*\"})"
    }
   ]
  },
  {
   "title": "Expired",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((x509_cert_not_after{job=\"certificates-exporter\", subject_O=~\"Ericsson.*\"} - time()) / 86400) < bool 0)"
    }
   ]
  },
  {
   "title": "Expiring within $critical_threshold days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(0 < ((x509_cert_not_after{job=\"certificates-exporter\", subject_O=~\"Ericsson.*\"} - time()) / 86400) < bool $critical_threshold)"
    }
   ]
  },
  {
   "title": "Expiring within $warning_threshold days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(0 < ((x509_cert_not_after{job=\"certificates-exporter\", subject_O=~\"Ericsson.*\"} - time()) / 86400) < bool $warning_threshold)"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(x509_read_errors)" }
   ]
  },
  {
   "title": "Exporter Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(x509_read_errors)" }
   ]
  },
  { "title": "Expiration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Kubernetes Secrets (time left < $list_threshold days)",
   "type": "table",
   "description": "Because of a missing feature in Grafana, critical and warning thresholds from dashboard variables will not affect coloration of the Time Left column in this table.\n\nThresholds are to be set manually in the Overrides settings for this widget.\n\nPlease vote or contribute to issue : https://github.com/grafana/grafana/issues/922",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sort(((x509_cert_not_after{secret_name!=\"\",  job=\"certificates-exporter\", subject_O=~\"Ericsson.*\"} - time())/86400) < 180)"
    }
   ]
  },
  {
   "title": "Total Certificates List",
   "type": "table",
   "description": "Because of a missing feature in Grafana, critical and warning thresholds from dashboard variables will not affect coloration of the Time Left column in this table.\n\nThresholds are to be set manually in the Overrides settings for this widget.\n\nPlease vote or contribute to issue : https://github.com/grafana/grafana/issues/922",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "x509_cert_not_after{job=\"certificates-exporter\", subject_O=~\"Ericsson.*\"}"
    }
   ]
  },
  { "title": "Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Kubernetes Secrets : Shortest Validity Period",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "bottomk(10, (x509_cert_not_after{secret_name!=\"\",job=\"certificates-exporter\", subject_O=~\"Ericsson.*\"} - x509_cert_not_before) / 86400)"
    }
   ]
  },
  {
   "title": "Kubernetes Secrets : Longest Validity Period",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "topk(10, (x509_cert_not_after{secret_name!=\"\",job=\"certificates-exporter\", subject_O=~\"Ericsson.*\"} - x509_cert_not_before) / 86400)"
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } }
 ]
}