{
 "title": "BNEW Deployments and EIAP version",
 "description": "Display the EIAP helmfile version installed on ${environment}",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "ossbmas01,oss,ossbnew02,ossecos01,ossdev01,ossern01,ossbnew03,idunopenlab01,idunossautoapp01,ossviavi01,ossinfov01,osscransco01,ossprototype01,ossbnew05"
   },
   {
    "name": "helmfile_version",
    "label": "helmfile_version",
    "query": {
     "query": "label_values(kube_namespace_annotations, annotation_idunaas_installed_helmfile)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"background-color:  #002561;text-align: center\">\n   BNEW EIAP Deployments Helmfile Version\n</h1>\n<p style=\"font-style: italic\">Helmfile Version of current Installed EIAP in BNEW Deployments</p>\n<hr width=\"100%\" />\n<br>\n<table style=\"border:1px solid black;width:30%\"> \n   <tr>\n    <th style=\"background-color: #696969\">Panel Color</th>\n    <th style=\"background-color: #696969\">Indicates</th>\n       \n  </tr> \n  <tr>\n    <td style=\"color: Green\">Green</td>\n    <td>Successful EIAP Installation</td>\n      \n  </tr>\n  <tr>\n    <td style=\"color: Orange\">Orange</td>\n    <td>Upgrade progressing / Deployment Issue</td>     \n  </tr>  \n  </table>"
   }
  },
  { "title": "BNEW Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "bnewidun01",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_namespace_annotations{namespace=\"oss\"}",
     "legendFormat": "{{ annotation_idunaas_installed_helmfile }}"
    }
   ]
  },
  {
   "title": "bnewidun02",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_namespace_annotations{namespace=\"ossbnew02\"}",
     "legendFormat": "{{ annotation_idunaas_installed_helmfile }}"
    }
   ]
  },
  {
   "title": "bnewidun03",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_namespace_annotations{namespace=\"ossbnew03\"}",
     "legendFormat": "{{ annotation_idunaas_installed_helmfile }}"
    }
   ]
  },
  {
   "title": "bnewidun05",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_namespace_annotations{namespace=\"ossbnew05\"}",
     "legendFormat": "{{ annotation_idunaas_installed_helmfile }}"
    }
   ]
  },
  {
   "title": "bnew03",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_namespace_annotations{namespace=\"ossbnew03\"}",
     "legendFormat": "{{ annotation_idunaas_installed_helmfile }}"
    }
   ]
  }
 ]
}