{{- if .Values.clusterRole.create -}}

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "idunaas-custom-exporter.clusterRoleName" . }}
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ["list","get","watch"]
{{- end }}