{{- if .Values.kpi.metrics_collector -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "idunaas-custom-exporter.fullname" . }}-kpi
data:
  KPI_COLLECTOR: "{{ .Values.kpi.metrics_collector}}"
  EIC_NAMESPACE: "{{ .Values.eic_namespace}}"
{{- end }}