apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "idunaas-custom-exporter.fullname" . }}
  labels:
    {{- include "idunaas-custom-exporter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "idunaas-custom-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "idunaas-custom-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "idunaas-custom-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "idunaas-custom-exporter.fullname" . }}-general
             {{- if .Values.monitoring.helm_stats }}
            - configMapRef:
                name: {{ include "idunaas-custom-exporter.fullname" . }}-helmstats
             {{- end }}
             {{- if .Values.kpi.metrics_collector }}
            - configMapRef:
                name: {{ include "idunaas-custom-exporter.fullname" . }}-kpi
             {{- end }}
             {{- if .Values.countApps.enabled }}
            - configMapRef:
                name: {{ include "idunaas-custom-exporter.fullname" . }}-conf-rapps
            - secretRef:
                name: {{ include "idunaas-custom-exporter.fullname" . }}-sec-rapps
             {{- end }}
          ports:
            - name: http
              containerPort: 8008
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.subsystems_conf_ini }}
          volumeMounts:
            - name: config-ini
              mountPath: "/config"
      volumes:
        - name: config-ini
          secret:
            secretName: {{ include "idunaas-custom-exporter.fullname" . }}-sec-subsystems-config-ini
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
