{{- if .Values.countApps.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "idunaas-custom-exporter.fullname" . }}-sec-rapps
stringData:
  APPS_USER:   "{{ .Values.countApps.username }}"
  APPS_PASSWD: "{{ .Values.countApps.passwd }}"
{{- end }}