{{- if .Values.subsystems_conf_ini -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idunaas-custom-exporter.fullname" . }}-sec-subsystems-config-ini
type: Opaque
stringData:
  config.ini: |{{ .Values.subsystems_conf_ini | nindent 4 }}
{{- end }}