{
 "title": "EIAPaaS Deployment Utilization Detail View",
 "description": "Displays the number of  user logins on a deployment",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "prometheus" },
   {
    "name": "loadbalancer",
    "label": "Load Balancer",
    "query": {
     "query": "label_values(aws_networkelb_active_flow_count_average{},load_balancer)"
    }
   }
  ]
 },
 "panels": [
  { "title": "User Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User logins",
   "type": "stat",
   "description": "User login history for deployment ${environment}",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(delta(keycloak_logins{client_id=\"eo\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Total user logins",
   "type": "timeseries",
   "description": "Total number of user logins on the deployments on ${environment}",
   "gridPos": { "h": 7, "w": 18, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(keycloak_logins{client_id=\"eo\"})",
     "legendFormat": "Sum"
    }
   ]
  },
  { "title": "Network Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Average Processed Bytes Past Hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(aws_networkelb_processed_bytes_sum{load_balancer=\"$loadbalancer\"}[1h])",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "Panel Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 16, "x": 6, "y": 9 },
   "options": {
    "content": "\n \n  Processed Bytes - The total number of bytes processed by the load balancer, including TCP/IP headers. This count includes traffic to and from targets, minus health check traffic.\n   \n  Active Flow Count - The total number of concurrent flows (or connections) from clients to targets.\n  \n  \n           "
   }
  },
  {
   "title": "ProcessedBytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_networkelb_processed_bytes_sum{load_balancer=~\"$loadbalancer\"}",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "Active Flow Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_networkelb_active_flow_count_average{load_balancer=\"$loadbalancer\"}",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  { "title": "Cost Explorer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "environment" },
  {
   "title": "Last Month Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aws_last_month_usage_costs", "legendFormat": "Last month usage" }
   ]
  },
  {
   "title": "MTD Costs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aws_month_usage_costs", "legendFormat": "MTD Usage" }
   ]
  },
  {
   "title": "Daily Cost Trends",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 10, "y": 29 },
   "targets": [
    { "expr": "aws_daily_usage_costs", "legendFormat": "Daily Usage" }
   ]
  }
 ]
}